version: '3.3'



services:
  redis:
    image: redis
    container_name: redis
    restart: always    
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    
  mongo:
    image: mongo
    container_name: mongo
    restart: always    
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always    
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin

  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always    
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data